name: StructureBoxes
main: io.github.eirikh1996.structureboxes.StructureBoxes
version: '${projectVersion}'
api-version: 1.18
author: eirikh1996
depend:
  - WorldEdit
softdepend:
  - WorldGuard
  - Movecraft
commands:
  structurebox:
    aliases:
      - sb
      - sbox
    usage: /structurebox <create|reload|undo>
permissions:
  structureboxes.undo:
    default: true
