Debug: false
Structure Box Item: chest
Structure Box Display Name: §6Structure Box
Max Structure Size: 10000
Max Session Time: 300 #Time in seconds
Alternative Display Names:
  - SiB
Structure Box Prefix: '§6Structure Box: '
Alternative Prefixes:
  - 'SiB: '
Structure Box Instruction Message: '§bPlace in a free space to spawn a structure'
Require permission per structure box: false
#Determines if the structure box must be placed inside of a region of supported anti-griefing plugins
Restrict to regions:
  Enabled: false
  Exceptions:
    - Merchantman
    - MM
Free space:
  Require free space: true
  Blocks to ignore:
    - long_grass
    - double_plant
    - stationary_water
    - water
    - lava
    - stationary_lava