Debug: false
Structure Box Item: chest
Structure Box Display Name: ยง6Structure Box
Max Structure Size: 10000
Max Session Time: 60
Alternative Display Names:
  - SiB
Structure Box Prefix: 'ยง6Structure Box: '
Alternative Prefixes:
  - 'SiB: '
Structure Box Instruction Message: ''

#Determines if the structure box must be placed inside of a region of supported anti-griefing plugins
Restrict to regions:
  Enabled: false
  Exceptions:
    - Merchantman
    - MM
Free space:
  Require free space: true
  Blocks to ignore:
    - tall_grass