Debug: false
Structure Box Item: chest
Structure Box Display Name: §6Structure Box
Max Structure Size: 10000
Max Session Time: 300
Place cooldown time: 10
Alternative Display Names:
  - SiB
Structure Box Prefix: '§6Structure Box: '
Alternative Prefixes:
  - 'SiB: '
Structure Box Instruction Message: '§bPlace in a free space to spawn a structure'
Require permission per structure box: false
Metrics: true
#Determines if the structure box must be placed inside of a region of supported anti-griefing plugins
Restrict to regions:
  Enabled: false
  Exceptions:
    - Merchantman
    - MM
#Settings for free space requirements
Free space:
  Require free space: true
  Blocks to ignore:
    - grass
    - tall_grass
    - fern
    - large_fern
    - double_plant
    - water
    - lava
    - kelp
    - kelp_plant
    - seagrass
    - tall_seagrass
    - dandelion
    - poppy
    - blue_orchid
    - allium
    - azure_bluet
    - red_tulip
    - orange_tulip
    - white_tulip
    - pink_tulip
    - oxeye_daisy
    - cornflower
    - lily_of_the_valley
    - wither_rose
    - sunflower
    - lilac
    - rose_bush
    - peony
    - sea_pickle
    - bubble_column