name: StructureBoxes
main: io.github.eirikh1996.structureboxes.StructureBoxes
version: ${project.version}
api-version: 1.13
depend:
  - WorldEdit
softdepend:
  - WorldGuard
  - RedProtect
  - Factions
  - GriefPrevention
  - Kingdoms
  - Towny
commands:
  structurebox:
    aliases:
      - sb
    usage: /structurebox <create|undo>